export const SET_PROJECT_NAME = 'SET_PROJECT_NAME'
export const REQUEST_EXPEDITION = 'REQUEST_EXPEDITION'
export const INITIALIZE_EXPEDITIONS = 'INITIALIZE_EXPEDITION'
export const REQUEST_DOCUMENTS = 'REQUEST_DOCUMENTS'
export const INITIALIZE_DOCUMENTS = 'INITIALIZE_DOCUMENTS'
export const SET_VIEWPORT = 'SET_VIEWPORT'
export const UPDATE_DATE = 'UPDATE_DATE'
export const SELECT_PLAYBACK_MODE = 'SELECT_PLAYBACK_MODE'
export const SELECT_FOCUS_TYPE = 'SELECT_FOCUS_TYPE'
export const SELECT_ZOOM = 'SELECT_ZOOM'
export const TOGGLE_SENSOR_DATA = 'TOGGLE_SENSOR_DATA'
export const JUMP_TO = 'JUMP_TO'
export const SET_MOUSE_POSITION = 'SET_MOUSE_POSITION'
export const SET_ZOOM = 'SET_ZOOM'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const OPEN_EXPEDITION_PANEL = 'OPEN_EXPEDITION_PANEL'
export const CLOSE_EXPEDITION_PANEL = 'CLOSE_EXPEDITION_PANEL'
export const OPEN_LIGHTBOX = 'OPEN_LIGHTBOX'
export const CLOSE_LIGHTBOX = 'CLOSE_LIGHTBOX'

export const BLANK = 'BLANK'

export const API_EXPEDITION_DOCS_GET = [
    'API_EXPEDITION_DOCS_START',
    'API_EXPEDITION_DOCS_SUCCESS',
    'API_EXPEDITION_DOCS_FAILURE',
];

export const API_PROJECT_EXPEDITIONS_GET = [
    'API_PROJECT_EXPEDITIONS_GET_START',
    'API_PROJECT_EXPEDITIONS_GET_SUCCESS',
    'API_PROJECT_EXPEDITIONS_GET_FAILURE',
];

export const API_EXPEDITION_GET = [
    'API_EXPEDITION_GET_START',
    'API_EXPEDITION_GET_SUCCESS',
    'API_EXPEDITION_GET_FAILURE',
];

export const API_PROJECT_GET = [
    'API_PROJECT_GET_START',
    'API_PROJECT_GET_SUCCESS',
    'API_PROJECT_GET_FAILURE',
];
