export const REQUEST_EXPEDITION = 'REQUEST_EXPEDITION'
export const INITIALIZE_EXPEDITIONS = 'INITIALIZE_EXPEDITION'
export const REQUEST_DOCUMENTS = 'REQUEST_DOCUMENTS'
export const INITIALIZE_DOCUMENTS = 'INITIALIZE_DOCUMENTS'
export const SELECT_FOCUS_TYPE = 'SELECT_FOCUS_TYPE'

// Timeline

export const UPDATE_DATE = 'UPDATE_DATE'
export const SELECT_PLAYBACK_MODE = 'SELECT_PLAYBACK_MODE'
export const TIMELINE_CHANGE_PLAYBACK_MODE = 'TIMELINE_CHANGE_PLAYBACK_MODE'
export const TIMELINE_SCRUB = 'TIMELINE_SCRUBE'

// Viewport

export const SET_VIEWPORT = 'SET_VIEWPORT'
export const SELECT_ZOOM = 'SELECT_ZOOM'
export const SET_ZOOM = 'SET_ZOOM'

// General UI

export const SET_MOUSE_POSITION = 'SET_MOUSE_POSITION'

export const OPEN_LIGHTBOX = 'OPEN_LIGHTBOX'
export const CLOSE_LIGHTBOX = 'CLOSE_LIGHTBOX'

export const OPEN_EXPEDITION_PANEL = 'OPEN_EXPEDITION_PANEL'
export const CLOSE_EXPEDITION_PANEL = 'CLOSE_EXPEDITION_PANEL'

function expandApiTypes(base) {
    return {
        'START': base + "_START",
        'SUCCESS': base + "_SUCCESS",
        'FAILURE': base + "_FAILURE",
    }
}

export const API_EXPEDITION_DOCS_GET = expandApiTypes("API_EXPEDITION_DOCS_GET")
export const API_PROJECT_EXPEDITIONS_GET = expandApiTypes("API_PROJECT_EXPEDITIONS_GET")
export const API_EXPEDITION_GET = expandApiTypes("API_EXPEDITION_GET")
export const API_PROJECT_GET = expandApiTypes("API_PROJECT_GET")

