#+TITLE:  README for cloud
#+EMAIL:  jacob@conservify.org 

* Overview
  This repository contains:

  1) All backend server side code, mostly written in Golang.

  2) All public facing web sites, specifically the administrative site and the non-authenticated frontend.

  3) PostgreSQL schema and sample/seed data.

* Developer Instructions 
*** Machine Setup
**** Linux
     1. Install docker, nodejs, and yarn.
        sudo apt-get install docker.io docker-compose 
        npm install -g yarn
     2. Configure docker
        sudo gpasswd -a $USER docker
        newgrp docker 
        docker ps -a # testing
     3. Ensure you have the latest golang (>1.12)

**** OSX
     1. Install nodejs/npm (https://nodejs.org/en/download/)
     2. Install docker (https://docs.docker.com/docker-for-mac/install/)
     3. Ensure you have the latest golang (>1.12)

*** Running Locally
    1. Create development fieldkit.env

    echo FIELDKIT_ADDR=0.0.0.0:8080 > fieldkit.env
       
    2. Run the database.

    make restart-progress

    3. Run the fk server.

    ./run-server-containerless.sh

    4. Run one of the web sites in development mode.

    cd frontend
    yarn dev

* EOF
