INSERT INTO fieldkit.module_meta VALUES (1, 'fk.water.ph', 1, '{9}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (2, 'fk.water.ec', 1, '{16}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (3, 'fk.water.do', 1, '{17}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (4, 'fk.water.temp', 1, '{18}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (5, 'fk.water.orp', 1, '{19}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (6, 'fk.water.ph', 1, '{2}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (7, 'fk.water.ec', 1, '{2}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (8, 'fk.water.dox', 1, '{2}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (9, 'fk.water.do', 1, '{2}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (10, 'fk.water.temp', 1, '{2}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (11, 'fk.water.orp', 1, '{2}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (12, 'fk.weather', 1, '{1}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (13, 'fk.weather', 1, '{1}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (14, 'fk.distance', 1, '{3}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (15, 'fk.diagnostics', 1, '{161}', '{1}', true);
INSERT INTO fieldkit.module_meta VALUES (16, 'fk.random', 1, '{160}', '{1}', true);
INSERT INTO fieldkit.module_meta VALUES (17, 'fk.water', 1, '{2}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (18, 'fk.testing', 1, '{161}', '{1}', false);
INSERT INTO fieldkit.module_meta VALUES (19, 'wh.floodnet', 0, '{0}', '{0}', false);

INSERT INTO fieldkit.sensor_meta VALUES (1, 1, 0, 'ph', 'ph', 'fk.water.ph.ph', false, '', '{"en-us":{"label":"pH"}}', '[]', '[{"minimum":0,"maximum":14}]');
INSERT INTO fieldkit.sensor_meta VALUES (2, 2, 0, 'ec', 'ec', 'fk.water.ec.ec', false, 'μS/cm', '{"en-us":{"label":"Conductivity"}}', '[]', '[{"minimum":0,"maximum":500000}]');
INSERT INTO fieldkit.sensor_meta VALUES (3, 3, 0, 'do', 'do', 'fk.water.do.do', false, '%', '{"en-us":{"label":"DO"}}', '[]', '[{"minimum":0,"maximum":100}]');
INSERT INTO fieldkit.sensor_meta VALUES (4, 3, 1, 'pressure', 'pressure', 'fk.water.do.pressure', false, 'kPa', '{"en-us":{"label":"Pressure"}}', '[]', '[{"minimum":1,"maximum":200000}]');
INSERT INTO fieldkit.sensor_meta VALUES (5, 3, 2, 'temperature', 'temperature', 'fk.water.do.temperature', false, '°C', '{"en-us":{"label":"Temperature"}}', '[]', '[{"minimum":-100,"maximum":200}]');
INSERT INTO fieldkit.sensor_meta VALUES (6, 4, 0, 'temp', 'temp', 'fk.water.temp.temp', false, '°C', '{"en-us":{"label":"Temperature"}}', '[]', '[{"minimum":-126,"maximum":1254}]');
INSERT INTO fieldkit.sensor_meta VALUES (7, 5, 0, 'orp', 'orp', 'fk.water.orp.orp', false, 'mV', '{"en-us":{"label":"ORP"}}', '[]', '[{"minimum":-1019.9,"maximum":1019.9}]');
INSERT INTO fieldkit.sensor_meta VALUES (8, 6, 0, 'ph', 'ph', 'fk.water.ph.ph', false, '', '{"en-us":{"label":"pH"}}', '[]', '[{"minimum":0,"maximum":14}]');
INSERT INTO fieldkit.sensor_meta VALUES (9, 7, 0, 'ec', 'ec', 'fk.water.ec.ec', false, 'μS/cm', '{"en-us":{"label":"Conductivity"}}', '[]', '[{"minimum":0,"maximum":500000}]');
INSERT INTO fieldkit.sensor_meta VALUES (10, 7, 1, 'tds', 'tds', 'fk.water.ec.tds', false, '', '{"en-us":{"label":"TDS"}}', '[]', '[{"minimum":0,"maximum":0}]');
INSERT INTO fieldkit.sensor_meta VALUES (11, 7, 2, 'salinity', 'salinity', 'fk.water.ec.salinity', false, '', '{"en-us":{"label":"Salinity"}}', '[]', '[{"minimum":0,"maximum":0}]');
INSERT INTO fieldkit.sensor_meta VALUES (12, 8, 0, 'dox', 'dox', 'fk.water.dox.dox', false, '%', '{"en-us":{"label":"DO"}}', '[]', '[{"minimum":0,"maximum":100}]');
INSERT INTO fieldkit.sensor_meta VALUES (13, 9, 0, 'do', 'do', 'fk.water.do.do', false, '%', '{"en-us":{"label":"DO"}}', '[]', '[{"minimum":0,"maximum":100}]');
INSERT INTO fieldkit.sensor_meta VALUES (14, 10, 0, 'temp', 'temp', 'fk.water.temp.temp', false, '°C', '{"en-us":{"label":"Temperature"}}', '[]', '[{"minimum":-126,"maximum":1254}]');
INSERT INTO fieldkit.sensor_meta VALUES (15, 11, 0, 'orp', 'orp', 'fk.water.orp.orp', false, 'mV', '{"en-us":{"label":"ORP"}}', '[]', '[{"minimum":-1019.9,"maximum":1019.9}]');
INSERT INTO fieldkit.sensor_meta VALUES (16, 12, 0, 'humidity', 'humidity', 'fk.weather.humidity', false, '%', '{"en-us":{"label":"Humidity"}}', '[]', '[{"minimum":0,"maximum":100}]');
INSERT INTO fieldkit.sensor_meta VALUES (17, 12, 1, 'temperature1', 'temperature_1', 'fk.weather.temperature1', false, '°C', '{"en-us":{"label":"Temperature 1"}}', '[]', '[{"minimum":-100,"maximum":200}]');
INSERT INTO fieldkit.sensor_meta VALUES (18, 12, 2, 'pressure', 'pressure', 'fk.weather.pressure', false, 'kPa', '{"en-us":{"label":"Pressure"}}', '[]', '[{"minimum":1,"maximum":200000}]');
INSERT INTO fieldkit.sensor_meta VALUES (19, 12, 3, 'temperature2', 'temperature_2', 'fk.weather.temperature2', false, '°C', '{"en-us":{"label":"Temperature 2"}}', '[]', '[{"minimum":-100,"maximum":200}]');
INSERT INTO fieldkit.sensor_meta VALUES (20, 12, 4, 'rain', 'rain', 'fk.weather.rain', false, 'mm', '{"en-us":{"label":"Rain"}}', '[]', '[{"minimum":0,"maximum":1000}]');
INSERT INTO fieldkit.sensor_meta VALUES (21, 12, 5, 'windSpeed', 'wind_speed', 'fk.weather.windSpeed', false, 'km/hr', '{"en-us":{"label":"Wind Speed"}}', '[]', '[{"minimum":0,"maximum":500}]');
INSERT INTO fieldkit.sensor_meta VALUES (22, 12, 6, 'windDir', 'wind_dir', 'fk.weather.windDir', false, '°', '{"en-us":{"label":"Wind Direction"}}', '[]', '[{"minimum":0,"maximum":360}]');
INSERT INTO fieldkit.sensor_meta VALUES (23, 12, 7, 'windDirMv', 'wind_dir_mv', 'fk.weather.windDirMv', false, 'mV', '{"en-us":{"label":"Wind Direction Raw ADC"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (24, 12, 8, 'windHrMaxSpeed', 'wind_hr_max_speed', 'fk.weather.windHrMaxSpeed', false, 'km/hr', '{"en-us":{"label":"Wind Max Speed (1 hour)"}}', '[]', '[{"minimum":0,"maximum":500}]');
INSERT INTO fieldkit.sensor_meta VALUES (25, 12, 9, 'windHrMaxDir', 'wind_hr_max_dir', 'fk.weather.windHrMaxDir', false, '°', '{"en-us":{"label":"Wind Max Direction (1 hour)"}}', '[]', '[{"minimum":0,"maximum":360}]');
INSERT INTO fieldkit.sensor_meta VALUES (26, 12, 10, 'wind10mMaxSpeed', 'wind_10m_max_speed', 'fk.weather.wind10mMaxSpeed', false, 'km/hr', '{"en-us":{"label":"Wind Max Speed (10 min)"}}', '[]', '[{"minimum":0,"maximum":500}]');
INSERT INTO fieldkit.sensor_meta VALUES (27, 12, 11, 'wind10mMaxDir', 'wind_10m_max_dir', 'fk.weather.wind10mMaxDir', false, '°', '{"en-us":{"label":"Wind Max Direction (10 min)"}}', '[]', '[{"minimum":0,"maximum":360}]');
INSERT INTO fieldkit.sensor_meta VALUES (28, 12, 12, 'wind2mAvgSpeed', 'wind_2m_avg_speed', 'fk.weather.wind2mAvgSpeed', false, 'km/hr', '{"en-us":{"label":"Wind Average Speed (2 min)"}}', '[]', '[{"minimum":0,"maximum":500}]');
INSERT INTO fieldkit.sensor_meta VALUES (29, 12, 13, 'wind2mAvgDir', 'wind_2m_avg_dir', 'fk.weather.wind2mAvgDir', false, '°', '{"en-us":{"label":"Wind Average Direction (2 min)"}}', '[]', '[{"minimum":0,"maximum":360}]');
INSERT INTO fieldkit.sensor_meta VALUES (30, 12, 14, 'rainThisHour', 'rain_this_hour', 'fk.weather.rainThisHour', false, 'mm', '{"en-us":{"label":"Rain This Hour"}}', '[]', '[{"minimum":0,"maximum":1000}]');
INSERT INTO fieldkit.sensor_meta VALUES (31, 12, 15, 'rainPrevHour', 'rain_prev_hour', 'fk.weather.rainPrevHour', false, 'mm', '{"en-us":{"label":"Rain Previous Hour"}}', '[]', '[{"minimum":0,"maximum":1000}]');
INSERT INTO fieldkit.sensor_meta VALUES (32, 13, 0, 'humidity', 'humidity', 'fk.weather.humidity', false, '%', '{"en-us":{"label":"Humidity"}}', '[]', '[{"minimum":0,"maximum":100}]');
INSERT INTO fieldkit.sensor_meta VALUES (33, 13, 1, 'temperature1', 'temperature_1', 'fk.weather.temperature1', false, '°C', '{"en-us":{"label":"Temperature 1"}}', '[]', '[{"minimum":-100,"maximum":200}]');
INSERT INTO fieldkit.sensor_meta VALUES (34, 13, 2, 'pressure', 'pressure', 'fk.weather.pressure', false, 'kPa', '{"en-us":{"label":"Pressure"}}', '[]', '[{"minimum":1,"maximum":200000}]');
INSERT INTO fieldkit.sensor_meta VALUES (35, 13, 3, 'temperature2', 'temperature_2', 'fk.weather.temperature2', false, '°C', '{"en-us":{"label":"Temperature 2"}}', '[]', '[{"minimum":-100,"maximum":200}]');
INSERT INTO fieldkit.sensor_meta VALUES (36, 13, 4, 'rain', 'rain', 'fk.weather.rain', false, 'mm', '{"en-us":{"label":"Rain"}}', '[]', '[{"minimum":0,"maximum":1000}]');
INSERT INTO fieldkit.sensor_meta VALUES (37, 13, 5, 'wind', 'wind', 'fk.weather.wind', false, 'km/hr', '{"en-us":{"label":"Wind"}}', '[]', '[{"minimum":0,"maximum":500}]');
INSERT INTO fieldkit.sensor_meta VALUES (38, 13, 6, 'windDir', 'wind_dir', 'fk.weather.windDir', false, '°', '{"en-us":{"label":"Wind Direction"}}', '[]', '[{"minimum":0,"maximum":360}]');
INSERT INTO fieldkit.sensor_meta VALUES (39, 13, 7, 'windMv', 'wind_mv', 'fk.weather.windMv', false, 'mV', '{"en-us":{"label":"Wind Raw ADC"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (40, 14, 0, 'distance', 'distance', 'fk.distance.distance', false, 'mm', '{"en-us":{"label":"Distance"}}', '[]', '[{"minimum":0,"maximum":4999}]');
INSERT INTO fieldkit.sensor_meta VALUES (41, 14, 1, 'distance0', 'distance_0', 'fk.distance.distance0', false, 'mm', '{"en-us":{"label":"Distance 0"}}', '[]', '[{"minimum":0,"maximum":4999}]');
INSERT INTO fieldkit.sensor_meta VALUES (42, 14, 2, 'distance1', 'distance_1', 'fk.distance.distance1', false, 'mm', '{"en-us":{"label":"Distance 1"}}', '[]', '[{"minimum":0,"maximum":4999}]');
INSERT INTO fieldkit.sensor_meta VALUES (43, 14, 3, 'distance2', 'distance_2', 'fk.distance.distance2', false, 'mm', '{"en-us":{"label":"Distance 2"}}', '[]', '[{"minimum":0,"maximum":4999}]');
INSERT INTO fieldkit.sensor_meta VALUES (44, 14, 4, 'calibration', 'calibration', 'fk.distance.calibration', false, 'mm', '{"en-us":{"label":"Calibration"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (45, 15, 0, 'batteryCharge', 'battery_charge', 'fk.diagnostics.batteryCharge', false, '', '{"en-us":{"label":"Battery Charge"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (46, 15, 1, 'batteryVoltage', 'battery_voltage', 'fk.diagnostics.batteryVoltage', false, 'V', '{"en-us":{"label":"Battery Voltage"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (47, 15, 2, 'batteryVbus', 'battery_vbus', 'fk.diagnostics.batteryVbus', false, 'V', '{"en-us":{"label":"Battery Bus Voltage"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (48, 15, 3, 'batteryVs', 'battery_vs', 'fk.diagnostics.batteryVs', false, 'mv', '{"en-us":{"label":"Battery Shunt Voltage"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (49, 15, 4, 'batteryMa', 'battery_ma', 'fk.diagnostics.batteryMa', false, 'ma', '{"en-us":{"label":"Battery Current"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (50, 15, 5, 'batteryPower', 'battery_power', 'fk.diagnostics.batteryPower', false, '', '{"en-us":{"label":"Battery Power"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (51, 15, 6, 'solarVbus', 'solar_vbus', 'fk.diagnostics.solarVbus', false, 'V', '{"en-us":{}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (52, 15, 7, 'solarVs', 'solar_vs', 'fk.diagnostics.solarVs', false, 'mv', '{"en-us":{}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (53, 15, 8, 'solarMa', 'solar_ma', 'fk.diagnostics.solarMa', false, 'ma', '{"en-us":{}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (54, 15, 9, 'solarPower', 'solar_power', 'fk.diagnostics.solarPower', false, '', '{"en-us":{}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (55, 15, 10, 'freeMemory', 'free_memory', 'fk.diagnostics.freeMemory', false, 'bytes', '{"en-us":{"label":"Free Memory"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (56, 15, 11, 'uptime', 'uptime', 'fk.diagnostics.uptime', false, 'ms', '{"en-us":{"label":"Uptime"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (57, 15, 12, 'temperature', 'temperature', 'fk.diagnostics.temperature', false, '°C', '{"en-us":{"label":"Temperature"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (58, 16, 0, 'random0', 'random_0', 'fk.random.random0', false, '', '{"en-us":{"label":"Random 0"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (59, 16, 1, 'random1', 'random_1', 'fk.random.random1', false, '', '{"en-us":{"label":"Random 1"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (60, 16, 2, 'random2', 'random_2', 'fk.random.random2', false, '', '{"en-us":{"label":"Random 2"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (61, 16, 3, 'random3', 'random_3', 'fk.random.random3', false, '', '{"en-us":{"label":"Random 3"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (62, 16, 4, 'random4', 'random_4', 'fk.random.random4', false, '', '{"en-us":{"label":"Random 4"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (63, 16, 5, 'random5', 'random_5', 'fk.random.random5', false, '', '{"en-us":{"label":"Random 5"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (64, 16, 6, 'random6', 'random_6', 'fk.random.random6', false, '', '{"en-us":{"label":"Random 6"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (65, 16, 7, 'random7', 'random_7', 'fk.random.random7', false, '', '{"en-us":{"label":"Random 7"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (66, 16, 8, 'random8', 'random_8', 'fk.random.random8', false, '', '{"en-us":{"label":"Random 8"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (67, 16, 9, 'random9', 'random_9', 'fk.random.random9', false, '', '{"en-us":{"label":"Random 9"}}', '[]', '[]');
INSERT INTO fieldkit.sensor_meta VALUES (68, 18, 0, 'sin', 'sin', 'fk.testing.sin', false, '', '{"en-us":{"label":"Sin(x)"}}', '[]', '[{"minimum":-1,"maximum":1}]');
INSERT INTO fieldkit.sensor_meta VALUES (69, 18, 1, 'saw.weekly', 'saw.weekly', 'fk.testing.saw.weekly', false, '', '{"en-us":{"label":"Saw(x)"}}', '[]', '[{"minimum":0,"maximum":1000}]');
INSERT INTO fieldkit.sensor_meta VALUES (70, 19, 0, 'depth', 'depth', 'wh.floodnet.depth', false, 'inches', '{"en-us":{"label":"Depth"}}', '[{"name":"D3TimeSeriesGraph","disabled":false,"y_zero":true,"thresholds":{"label":{"en-US":"Severity of Flooding"},"levels":[{"label":{"en-US":"None"},"value":8,"color":"#00CCFF"},{"label":{"en-US":"Almost"},"value":8.5,"color":"#0099FF"},{"label":{"en-US":"Some"},"value":9,"color":"#0066FF"},{"label":{"en-US":"Flooding"},"value":9.5,"color":"#0033FF"},{"label":{"en-US":"Severe"},"value":10,"color":"#0000FF"}]}}]', '[{"minimum":0,"maximum":40}]');
INSERT INTO fieldkit.sensor_meta VALUES (71, 19, 1, 'depthUnfiltered', 'depth_unfiltered', 'wh.floodnet.depthUnfiltered', true, 'inches', '{"en-us":{"label":"Depth (Unfiltered)"}}', '[{"name":"D3TimeSeriesGraph","disabled":false,"y_zero":false,"thresholds":null},{"name":"D3Map","disabled":false,"y_zero":false,"thresholds":null}]', '[{"minimum":0,"maximum":40}]');
INSERT INTO fieldkit.sensor_meta VALUES (72, 19, 2, 'distance', 'distance', 'wh.floodnet.distance', true, 'mm', '{"en-us":{"label":"Distance"}}', '[{"name":"D3TimeSeriesGraph","disabled":false,"y_zero":false,"thresholds":null},{"name":"D3Map","disabled":false,"y_zero":false,"thresholds":null}]', '[{"minimum":0,"maximum":4999}]');
INSERT INTO fieldkit.sensor_meta VALUES (73, 19, 3, 'battery', 'battery', 'wh.floodnet.battery', false, '%', '{"en-us":{"label":"Battery"}}', '[{"name":"D3TimeSeriesGraph","disabled":false,"y_zero":false,"thresholds":null},{"name":"D3Map","disabled":false,"y_zero":false,"thresholds":null}]', '[{"minimum":0,"maximum":100}]');
INSERT INTO fieldkit.sensor_meta VALUES (74, 19, 4, 'tideFeet', 'tide_feet', 'wh.floodnet.tideFeet', false, 'inches', '{"en-us":{"label":"Tide Level"}}', '[{"name":"D3TimeSeriesGraph","disabled":false,"y_zero":false,"thresholds":null},{"name":"D3Map","disabled":false,"y_zero":false,"thresholds":null}]', '[{"minimum":0,"maximum":4999}]');
INSERT INTO fieldkit.sensor_meta VALUES (75, 19, 5, 'humidity', 'humidity', 'wh.floodnet.humidity', true, '%', '{"en-us":{"label":"Humidity"}}', '[{"name":"D3TimeSeriesGraph","disabled":false,"y_zero":false,"thresholds":null},{"name":"D3Map","disabled":false,"y_zero":false,"thresholds":null}]', '[{"minimum":0,"maximum":100}]');
INSERT INTO fieldkit.sensor_meta VALUES (76, 19, 6, 'pressure', 'pressure', 'wh.floodnet.pressure', true, 'kPa', '{"en-us":{"label":"Pressure"}}', '[{"name":"D3TimeSeriesGraph","disabled":false,"y_zero":false,"thresholds":null},{"name":"D3Map","disabled":false,"y_zero":false,"thresholds":null}]', '[{"minimum":1,"maximum":200000}]');
INSERT INTO fieldkit.sensor_meta VALUES (77, 19, 7, 'altitude', 'altitude', 'wh.floodnet.altitude', true, 'm', '{"en-us":{"label":"Altitude"}}', '[{"name":"D3TimeSeriesGraph","disabled":false,"y_zero":false,"thresholds":null},{"name":"D3Map","disabled":false,"y_zero":false,"thresholds":null}]', '[{"minimum":3000,"maximum":-500}]');
INSERT INTO fieldkit.sensor_meta VALUES (78, 19, 8, 'temperature', 'temperature', 'wh.floodnet.temperature', true, '°C', '{"en-us":{"label":"Temperature"}}', '[{"name":"D3TimeSeriesGraph","disabled":false,"y_zero":false,"thresholds":null},{"name":"D3Map","disabled":false,"y_zero":false,"thresholds":null}]', '[{"minimum":-100,"maximum":200}]');
INSERT INTO fieldkit.sensor_meta VALUES (79, 19, 9, 'sdError', 'sdError', 'wh.floodnet.sdError', true, '', '{"en-us":{"label":"SD Error"}}', '[{"name":"D3TimeSeriesGraph","disabled":false,"y_zero":false,"thresholds":null},{"name":"D3Map","disabled":false,"y_zero":false,"thresholds":null}]', '[{"minimum":0,"maximum":200}]');