DROP MATERIALIZED VIEW IF EXISTS fieldkit.sensor_data_365d;
DROP MATERIALIZED VIEW IF EXISTS fieldkit.sensor_data_7d;
DROP MATERIALIZED VIEW IF EXISTS fieldkit.sensor_data_24h;
DROP MATERIALIZED VIEW IF EXISTS fieldkit.sensor_data_6h;
DROP MATERIALIZED VIEW IF EXISTS fieldkit.sensor_data_1h;
DROP MATERIALIZED VIEW IF EXISTS fieldkit.sensor_data_10m;