// Code generated by goagen v1.4.0, DO NOT EDIT.
//
// API "fieldkit": data Resource Client
//
// Command:
// $ main

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// DeviceDataDataPath computes a request path to the device data action of data.
func DeviceDataDataPath(deviceID string) string {
	param0 := deviceID

	return fmt.Sprintf("/data/devices/%s/data", param0)
}

// Retrieve data
func (c *Client) DeviceDataData(ctx context.Context, path string, firstBlock *int, lastBlock *int, page *int, pageSize *int) (*http.Response, error) {
	req, err := c.NewDeviceDataDataRequest(ctx, path, firstBlock, lastBlock, page, pageSize)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeviceDataDataRequest create the request corresponding to the device data action endpoint of the data resource.
func (c *Client) NewDeviceDataDataRequest(ctx context.Context, path string, firstBlock *int, lastBlock *int, page *int, pageSize *int) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if firstBlock != nil {
		tmp123 := strconv.Itoa(*firstBlock)
		values.Set("firstBlock", tmp123)
	}
	if lastBlock != nil {
		tmp124 := strconv.Itoa(*lastBlock)
		values.Set("lastBlock", tmp124)
	}
	if page != nil {
		tmp125 := strconv.Itoa(*page)
		values.Set("page", tmp125)
	}
	if pageSize != nil {
		tmp126 := strconv.Itoa(*pageSize)
		values.Set("pageSize", tmp126)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// DeviceSummaryDataPath computes a request path to the device summary action of data.
func DeviceSummaryDataPath(deviceID string) string {
	param0 := deviceID

	return fmt.Sprintf("/data/devices/%s/summary", param0)
}

// Retrieve summary
func (c *Client) DeviceSummaryData(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDeviceSummaryDataRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeviceSummaryDataRequest create the request corresponding to the device summary action endpoint of the data resource.
func (c *Client) NewDeviceSummaryDataRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
