// Code generated by goagen v1.4.0, DO NOT EDIT.
//
// API "fieldkit": data Resource Client
//
// Command:
// $ main

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// DeleteDataPath computes a request path to the delete action of data.
func DeleteDataPath(ingestionID int) string {
	param0 := strconv.Itoa(ingestionID)

	return fmt.Sprintf("/data/ingestions/%s", param0)
}

// Delete data
func (c *Client) DeleteData(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDeleteDataRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeleteDataRequest create the request corresponding to the delete action endpoint of the data resource.
func (c *Client) NewDeleteDataRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// DeviceDataPath computes a request path to the device action of data.
func DeviceDataPath(deviceID string) string {
	param0 := deviceID

	return fmt.Sprintf("/data/devices/%s", param0)
}

// Retrieve data
func (c *Client) DeviceData(ctx context.Context, path string, firstBlock *int, lastBlock *int, pageNumber *int, pageSize *int) (*http.Response, error) {
	req, err := c.NewDeviceDataRequest(ctx, path, firstBlock, lastBlock, pageNumber, pageSize)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeviceDataRequest create the request corresponding to the device action endpoint of the data resource.
func (c *Client) NewDeviceDataRequest(ctx context.Context, path string, firstBlock *int, lastBlock *int, pageNumber *int, pageSize *int) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if firstBlock != nil {
		tmp181 := strconv.Itoa(*firstBlock)
		values.Set("firstBlock", tmp181)
	}
	if lastBlock != nil {
		tmp182 := strconv.Itoa(*lastBlock)
		values.Set("lastBlock", tmp182)
	}
	if pageNumber != nil {
		tmp183 := strconv.Itoa(*pageNumber)
		values.Set("pageNumber", tmp183)
	}
	if pageSize != nil {
		tmp184 := strconv.Itoa(*pageSize)
		values.Set("pageSize", tmp184)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ProcessDataPath computes a request path to the process action of data.
func ProcessDataPath() string {

	return fmt.Sprintf("/data/process")
}

// Process data
func (c *Client) ProcessData(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewProcessDataRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewProcessDataRequest create the request corresponding to the process action endpoint of the data resource.
func (c *Client) NewProcessDataRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
