// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "fieldkit": Export Resource Client
//
// Command:
// $ main

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// ListByInputExportPath computes a request path to the list by input action of Export.
func ListByInputExportPath(inputID int) string {
	param0 := strconv.Itoa(inputID)

	return fmt.Sprintf("/inputs/%s/csv", param0)
}

// Export data for an input.
func (c *Client) ListByInputExport(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListByInputExportRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListByInputExportRequest create the request corresponding to the list by input action endpoint of the Export resource.
func (c *Client) NewListByInputExportRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
