// Code generated by goagen v1.4.0, DO NOT EDIT.
//
// API "fieldkit": jsonData Resource Client
//
// Command:
// $ main

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// GetJSONDataPath computes a request path to the get action of jsonData.
func GetJSONDataPath(deviceID string) string {
	param0 := deviceID

	return fmt.Sprintf("/data/devices/%s/data/json", param0)
}

// Retrieve data
func (c *Client) GetJSONData(ctx context.Context, path string, end *int, internal *bool, pageNumber *int, pageSize *int, start *int) (*http.Response, error) {
	req, err := c.NewGetJSONDataRequest(ctx, path, end, internal, pageNumber, pageSize, start)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetJSONDataRequest create the request corresponding to the get action endpoint of the jsonData resource.
func (c *Client) NewGetJSONDataRequest(ctx context.Context, path string, end *int, internal *bool, pageNumber *int, pageSize *int, start *int) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if end != nil {
		tmp219 := strconv.Itoa(*end)
		values.Set("end", tmp219)
	}
	if internal != nil {
		tmp220 := strconv.FormatBool(*internal)
		values.Set("internal", tmp220)
	}
	if pageNumber != nil {
		tmp221 := strconv.Itoa(*pageNumber)
		values.Set("pageNumber", tmp221)
	}
	if pageSize != nil {
		tmp222 := strconv.Itoa(*pageSize)
		values.Set("pageSize", tmp222)
	}
	if start != nil {
		tmp223 := strconv.Itoa(*start)
		values.Set("start", tmp223)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// GetLinesJSONDataPath computes a request path to the get lines action of jsonData.
func GetLinesJSONDataPath(deviceID string) string {
	param0 := deviceID

	return fmt.Sprintf("/data/devices/%s/data/lines", param0)
}

// Retrieve data
func (c *Client) GetLinesJSONData(ctx context.Context, path string, end *int, internal *bool, pageNumber *int, pageSize *int, start *int) (*http.Response, error) {
	req, err := c.NewGetLinesJSONDataRequest(ctx, path, end, internal, pageNumber, pageSize, start)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetLinesJSONDataRequest create the request corresponding to the get lines action endpoint of the jsonData resource.
func (c *Client) NewGetLinesJSONDataRequest(ctx context.Context, path string, end *int, internal *bool, pageNumber *int, pageSize *int, start *int) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if end != nil {
		tmp224 := strconv.Itoa(*end)
		values.Set("end", tmp224)
	}
	if internal != nil {
		tmp225 := strconv.FormatBool(*internal)
		values.Set("internal", tmp225)
	}
	if pageNumber != nil {
		tmp226 := strconv.Itoa(*pageNumber)
		values.Set("pageNumber", tmp226)
	}
	if pageSize != nil {
		tmp227 := strconv.Itoa(*pageSize)
		values.Set("pageSize", tmp227)
	}
	if start != nil {
		tmp228 := strconv.Itoa(*start)
		values.Set("start", tmp228)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
