// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "fieldkit": Application Media Types
//
// Command:
// $ main

package client

import (
	"github.com/goadesign/goa"
	"net/http"
	"time"
	"unicode/utf8"
)

// ProjectAdministrator media type (default view)
//
// Identifier: application/vnd.app.administrator+json; view=default
type ProjectAdministrator struct {
	ProjectID int `form:"projectId" json:"projectId" yaml:"projectId" xml:"projectId"`
	UserID    int `form:"userId" json:"userId" yaml:"userId" xml:"userId"`
}

// Validate validates the ProjectAdministrator media type instance.
func (mt *ProjectAdministrator) Validate() (err error) {

	return
}

// DecodeProjectAdministrator decodes the ProjectAdministrator instance encoded in resp body.
func (c *Client) DecodeProjectAdministrator(resp *http.Response) (*ProjectAdministrator, error) {
	var decoded ProjectAdministrator
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// ProjectAdministratorCollection is the media type for an array of ProjectAdministrator (default view)
//
// Identifier: application/vnd.app.administrator+json; type=collection; view=default
type ProjectAdministratorCollection []*ProjectAdministrator

// Validate validates the ProjectAdministratorCollection media type instance.
func (mt ProjectAdministratorCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeProjectAdministratorCollection decodes the ProjectAdministratorCollection instance encoded in resp body.
func (c *Client) DecodeProjectAdministratorCollection(resp *http.Response) (ProjectAdministratorCollection, error) {
	var decoded ProjectAdministratorCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// ProjectAdministrators media type (default view)
//
// Identifier: application/vnd.app.administrators+json; view=default
type ProjectAdministrators struct {
	Administrators ProjectAdministratorCollection `form:"administrators" json:"administrators" yaml:"administrators" xml:"administrators"`
}

// Validate validates the ProjectAdministrators media type instance.
func (mt *ProjectAdministrators) Validate() (err error) {
	if mt.Administrators == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "administrators"))
	}
	return
}

// DecodeProjectAdministrators decodes the ProjectAdministrators instance encoded in resp body.
func (c *Client) DecodeProjectAdministrators(resp *http.Response) (*ProjectAdministrators, error) {
	var decoded ProjectAdministrators
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// ClusterGeometrySummary media type (default view)
//
// Identifier: application/vnd.app.cluster_geometry_summary+json; view=default
type ClusterGeometrySummary struct {
	Geometry [][]float64 `form:"geometry" json:"geometry" yaml:"geometry" xml:"geometry"`
	ID       int         `form:"id" json:"id" yaml:"id" xml:"id"`
	SourceID int         `form:"sourceId" json:"sourceId" yaml:"sourceId" xml:"sourceId"`
}

// Validate validates the ClusterGeometrySummary media type instance.
func (mt *ClusterGeometrySummary) Validate() (err error) {

	if mt.Geometry == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "geometry"))
	}
	return
}

// DecodeClusterGeometrySummary decodes the ClusterGeometrySummary instance encoded in resp body.
func (c *Client) DecodeClusterGeometrySummary(resp *http.Response) (*ClusterGeometrySummary, error) {
	var decoded ClusterGeometrySummary
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// ClusterGeometrySummaryCollection is the media type for an array of ClusterGeometrySummary (default view)
//
// Identifier: application/vnd.app.cluster_geometry_summary+json; type=collection; view=default
type ClusterGeometrySummaryCollection []*ClusterGeometrySummary

// Validate validates the ClusterGeometrySummaryCollection media type instance.
func (mt ClusterGeometrySummaryCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeClusterGeometrySummaryCollection decodes the ClusterGeometrySummaryCollection instance encoded in resp body.
func (c *Client) DecodeClusterGeometrySummaryCollection(resp *http.Response) (ClusterGeometrySummaryCollection, error) {
	var decoded ClusterGeometrySummaryCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// DeviceSchema media type (default view)
//
// Identifier: application/vnd.app.device_schema+json; view=default
type DeviceSchema struct {
	Active     bool   `form:"active" json:"active" yaml:"active" xml:"active"`
	DeviceID   int    `form:"deviceId" json:"deviceId" yaml:"deviceId" xml:"deviceId"`
	JSONSchema string `form:"jsonSchema" json:"jsonSchema" yaml:"jsonSchema" xml:"jsonSchema"`
	Key        string `form:"key" json:"key" yaml:"key" xml:"key"`
	ProjectID  int    `form:"projectId" json:"projectId" yaml:"projectId" xml:"projectId"`
	SchemaID   int    `form:"schemaId" json:"schemaId" yaml:"schemaId" xml:"schemaId"`
}

// Validate validates the DeviceSchema media type instance.
func (mt *DeviceSchema) Validate() (err error) {

	if mt.JSONSchema == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "jsonSchema"))
	}
	if mt.Key == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "key"))
	}
	return
}

// DecodeDeviceSchema decodes the DeviceSchema instance encoded in resp body.
func (c *Client) DecodeDeviceSchema(resp *http.Response) (*DeviceSchema, error) {
	var decoded DeviceSchema
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// DeviceSchemaCollection is the media type for an array of DeviceSchema (default view)
//
// Identifier: application/vnd.app.device_schema+json; type=collection; view=default
type DeviceSchemaCollection []*DeviceSchema

// Validate validates the DeviceSchemaCollection media type instance.
func (mt DeviceSchemaCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeDeviceSchemaCollection decodes the DeviceSchemaCollection instance encoded in resp body.
func (c *Client) DecodeDeviceSchemaCollection(resp *http.Response) (DeviceSchemaCollection, error) {
	var decoded DeviceSchemaCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// DeviceSchemas media type (default view)
//
// Identifier: application/vnd.app.device_schemas+json; view=default
type DeviceSchemas struct {
	Schemas DeviceSchemaCollection `form:"schemas" json:"schemas" yaml:"schemas" xml:"schemas"`
}

// Validate validates the DeviceSchemas media type instance.
func (mt *DeviceSchemas) Validate() (err error) {
	if mt.Schemas == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "schemas"))
	}
	if err2 := mt.Schemas.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeDeviceSchemas decodes the DeviceSchemas instance encoded in resp body.
func (c *Client) DecodeDeviceSchemas(resp *http.Response) (*DeviceSchemas, error) {
	var decoded DeviceSchemas
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// DeviceSource media type (default view)
//
// Identifier: application/vnd.app.device_source+json; view=default
type DeviceSource struct {
	Active       bool   `form:"active" json:"active" yaml:"active" xml:"active"`
	ExpeditionID int    `form:"expeditionId" json:"expeditionId" yaml:"expeditionId" xml:"expeditionId"`
	ID           int    `form:"id" json:"id" yaml:"id" xml:"id"`
	Key          string `form:"key" json:"key" yaml:"key" xml:"key"`
	Name         string `form:"name" json:"name" yaml:"name" xml:"name"`
	TeamID       *int   `form:"teamId,omitempty" json:"teamId,omitempty" yaml:"teamId,omitempty" xml:"teamId,omitempty"`
	Token        string `form:"token" json:"token" yaml:"token" xml:"token"`
	UserID       *int   `form:"userId,omitempty" json:"userId,omitempty" yaml:"userId,omitempty" xml:"userId,omitempty"`
}

// Validate validates the DeviceSource media type instance.
func (mt *DeviceSource) Validate() (err error) {

	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	if mt.Token == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "token"))
	}
	if mt.Key == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "key"))
	}
	return
}

// DeviceSource media type (public view)
//
// Identifier: application/vnd.app.device_source+json; view=public
type DeviceSourcePublic struct {
	Active           bool        `form:"active" json:"active" yaml:"active" xml:"active"`
	Centroid         []float64   `form:"centroid,omitempty" json:"centroid,omitempty" yaml:"centroid,omitempty" xml:"centroid,omitempty"`
	EndTime          *time.Time  `form:"endTime,omitempty" json:"endTime,omitempty" yaml:"endTime,omitempty" xml:"endTime,omitempty"`
	Envelope         [][]float64 `form:"envelope,omitempty" json:"envelope,omitempty" yaml:"envelope,omitempty" xml:"envelope,omitempty"`
	ExpeditionID     int         `form:"expeditionId" json:"expeditionId" yaml:"expeditionId" xml:"expeditionId"`
	ID               int         `form:"id" json:"id" yaml:"id" xml:"id"`
	LastFeatureID    *int        `form:"lastFeatureId,omitempty" json:"lastFeatureId,omitempty" yaml:"lastFeatureId,omitempty" xml:"lastFeatureId,omitempty"`
	Name             string      `form:"name" json:"name" yaml:"name" xml:"name"`
	NumberOfFeatures *int        `form:"numberOfFeatures,omitempty" json:"numberOfFeatures,omitempty" yaml:"numberOfFeatures,omitempty" xml:"numberOfFeatures,omitempty"`
	Radius           *float64    `form:"radius,omitempty" json:"radius,omitempty" yaml:"radius,omitempty" xml:"radius,omitempty"`
	StartTime        *time.Time  `form:"startTime,omitempty" json:"startTime,omitempty" yaml:"startTime,omitempty" xml:"startTime,omitempty"`
	TeamID           *int        `form:"teamId,omitempty" json:"teamId,omitempty" yaml:"teamId,omitempty" xml:"teamId,omitempty"`
	UserID           *int        `form:"userId,omitempty" json:"userId,omitempty" yaml:"userId,omitempty" xml:"userId,omitempty"`
}

// Validate validates the DeviceSourcePublic media type instance.
func (mt *DeviceSourcePublic) Validate() (err error) {

	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	return
}

// DecodeDeviceSource decodes the DeviceSource instance encoded in resp body.
func (c *Client) DecodeDeviceSource(resp *http.Response) (*DeviceSource, error) {
	var decoded DeviceSource
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// DecodeDeviceSourcePublic decodes the DeviceSourcePublic instance encoded in resp body.
func (c *Client) DecodeDeviceSourcePublic(resp *http.Response) (*DeviceSourcePublic, error) {
	var decoded DeviceSourcePublic
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// DeviceSourceCollection is the media type for an array of DeviceSource (default view)
//
// Identifier: application/vnd.app.device_source+json; type=collection; view=default
type DeviceSourceCollection []*DeviceSource

// Validate validates the DeviceSourceCollection media type instance.
func (mt DeviceSourceCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DeviceSourceCollection is the media type for an array of DeviceSource (public view)
//
// Identifier: application/vnd.app.device_source+json; type=collection; view=public
type DeviceSourcePublicCollection []*DeviceSourcePublic

// Validate validates the DeviceSourcePublicCollection media type instance.
func (mt DeviceSourcePublicCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeDeviceSourceCollection decodes the DeviceSourceCollection instance encoded in resp body.
func (c *Client) DecodeDeviceSourceCollection(resp *http.Response) (DeviceSourceCollection, error) {
	var decoded DeviceSourceCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// DecodeDeviceSourcePublicCollection decodes the DeviceSourcePublicCollection instance encoded in resp body.
func (c *Client) DecodeDeviceSourcePublicCollection(resp *http.Response) (DeviceSourcePublicCollection, error) {
	var decoded DeviceSourcePublicCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// DeviceSources media type (default view)
//
// Identifier: application/vnd.app.device_sources+json; view=default
type DeviceSources struct {
	DeviceSources DeviceSourceCollection `form:"deviceSources" json:"deviceSources" yaml:"deviceSources" xml:"deviceSources"`
}

// Validate validates the DeviceSources media type instance.
func (mt *DeviceSources) Validate() (err error) {
	if mt.DeviceSources == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "deviceSources"))
	}
	if err2 := mt.DeviceSources.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeDeviceSources decodes the DeviceSources instance encoded in resp body.
func (c *Client) DecodeDeviceSources(resp *http.Response) (*DeviceSources, error) {
	var decoded DeviceSources
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// Expedition media type (default view)
//
// Identifier: application/vnd.app.expedition+json; view=default
type Expedition struct {
	Description string `form:"description" json:"description" yaml:"description" xml:"description"`
	ID          int    `form:"id" json:"id" yaml:"id" xml:"id"`
	Name        string `form:"name" json:"name" yaml:"name" xml:"name"`
	Slug        string `form:"slug" json:"slug" yaml:"slug" xml:"slug"`
}

// Validate validates the Expedition media type instance.
func (mt *Expedition) Validate() (err error) {

	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	if mt.Slug == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "slug"))
	}
	if mt.Description == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "description"))
	}
	if ok := goa.ValidatePattern(`^[[:alnum:]]+(-[[:alnum:]]+)*$`, mt.Slug); !ok {
		err = goa.MergeErrors(err, goa.InvalidPatternError(`response.slug`, mt.Slug, `^[[:alnum:]]+(-[[:alnum:]]+)*$`))
	}
	if utf8.RuneCountInString(mt.Slug) > 40 {
		err = goa.MergeErrors(err, goa.InvalidLengthError(`response.slug`, mt.Slug, utf8.RuneCountInString(mt.Slug), 40, false))
	}
	return
}

// Expedition media type (detailed view)
//
// Identifier: application/vnd.app.expedition+json; view=detailed
type ExpeditionDetailed struct {
	Centroid         []float64  `form:"centroid,omitempty" json:"centroid,omitempty" yaml:"centroid,omitempty" xml:"centroid,omitempty"`
	Description      string     `form:"description" json:"description" yaml:"description" xml:"description"`
	EndTime          *time.Time `form:"endTime,omitempty" json:"endTime,omitempty" yaml:"endTime,omitempty" xml:"endTime,omitempty"`
	ID               int        `form:"id" json:"id" yaml:"id" xml:"id"`
	LastFeatureID    *int       `form:"lastFeatureId,omitempty" json:"lastFeatureId,omitempty" yaml:"lastFeatureId,omitempty" xml:"lastFeatureId,omitempty"`
	Name             string     `form:"name" json:"name" yaml:"name" xml:"name"`
	NumberOfFeatures *int       `form:"numberOfFeatures,omitempty" json:"numberOfFeatures,omitempty" yaml:"numberOfFeatures,omitempty" xml:"numberOfFeatures,omitempty"`
	Radius           *float64   `form:"radius,omitempty" json:"radius,omitempty" yaml:"radius,omitempty" xml:"radius,omitempty"`
	Slug             string     `form:"slug" json:"slug" yaml:"slug" xml:"slug"`
	StartTime        *time.Time `form:"startTime,omitempty" json:"startTime,omitempty" yaml:"startTime,omitempty" xml:"startTime,omitempty"`
}

// Validate validates the ExpeditionDetailed media type instance.
func (mt *ExpeditionDetailed) Validate() (err error) {

	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	if mt.Slug == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "slug"))
	}
	if mt.Description == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "description"))
	}
	if ok := goa.ValidatePattern(`^[[:alnum:]]+(-[[:alnum:]]+)*$`, mt.Slug); !ok {
		err = goa.MergeErrors(err, goa.InvalidPatternError(`response.slug`, mt.Slug, `^[[:alnum:]]+(-[[:alnum:]]+)*$`))
	}
	if utf8.RuneCountInString(mt.Slug) > 40 {
		err = goa.MergeErrors(err, goa.InvalidLengthError(`response.slug`, mt.Slug, utf8.RuneCountInString(mt.Slug), 40, false))
	}
	return
}

// DecodeExpedition decodes the Expedition instance encoded in resp body.
func (c *Client) DecodeExpedition(resp *http.Response) (*Expedition, error) {
	var decoded Expedition
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// DecodeExpeditionDetailed decodes the ExpeditionDetailed instance encoded in resp body.
func (c *Client) DecodeExpeditionDetailed(resp *http.Response) (*ExpeditionDetailed, error) {
	var decoded ExpeditionDetailed
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// ExpeditionCollection is the media type for an array of Expedition (default view)
//
// Identifier: application/vnd.app.expedition+json; type=collection; view=default
type ExpeditionCollection []*Expedition

// Validate validates the ExpeditionCollection media type instance.
func (mt ExpeditionCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// ExpeditionCollection is the media type for an array of Expedition (detailed view)
//
// Identifier: application/vnd.app.expedition+json; type=collection; view=detailed
type ExpeditionDetailedCollection []*ExpeditionDetailed

// Validate validates the ExpeditionDetailedCollection media type instance.
func (mt ExpeditionDetailedCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeExpeditionCollection decodes the ExpeditionCollection instance encoded in resp body.
func (c *Client) DecodeExpeditionCollection(resp *http.Response) (ExpeditionCollection, error) {
	var decoded ExpeditionCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// DecodeExpeditionDetailedCollection decodes the ExpeditionDetailedCollection instance encoded in resp body.
func (c *Client) DecodeExpeditionDetailedCollection(resp *http.Response) (ExpeditionDetailedCollection, error) {
	var decoded ExpeditionDetailedCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// Expeditions media type (default view)
//
// Identifier: application/vnd.app.expeditions+json; view=default
type Expeditions struct {
	Expeditions ExpeditionCollection `form:"expeditions" json:"expeditions" yaml:"expeditions" xml:"expeditions"`
}

// Validate validates the Expeditions media type instance.
func (mt *Expeditions) Validate() (err error) {
	if mt.Expeditions == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "expeditions"))
	}
	if err2 := mt.Expeditions.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeExpeditions decodes the Expeditions instance encoded in resp body.
func (c *Client) DecodeExpeditions(resp *http.Response) (*Expeditions, error) {
	var decoded Expeditions
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// Firmwares media type (default view)
//
// Identifier: application/vnd.app.firmwares+json; view=default
type Firmwares struct {
	Firmwares FirmwareSummaryCollection `form:"firmwares" json:"firmwares" yaml:"firmwares" xml:"firmwares"`
}

// Validate validates the Firmwares media type instance.
func (mt *Firmwares) Validate() (err error) {
	if mt.Firmwares == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "firmwares"))
	}
	if err2 := mt.Firmwares.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeFirmwares decodes the Firmwares instance encoded in resp body.
func (c *Client) DecodeFirmwares(resp *http.Response) (*Firmwares, error) {
	var decoded Firmwares
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// GeoJSON media type (default view)
//
// Identifier: application/vnd.app.geojson+json; view=default
type GeoJSON struct {
	Features GeoJSONFeatureCollection `form:"features" json:"features" yaml:"features" xml:"features"`
	Type     string                   `form:"type" json:"type" yaml:"type" xml:"type"`
}

// Validate validates the GeoJSON media type instance.
func (mt *GeoJSON) Validate() (err error) {
	if mt.Type == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "type"))
	}
	if mt.Features == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "features"))
	}
	if err2 := mt.Features.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeGeoJSON decodes the GeoJSON instance encoded in resp body.
func (c *Client) DecodeGeoJSON(resp *http.Response) (*GeoJSON, error) {
	var decoded GeoJSON
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// GeoJSONFeature media type (default view)
//
// Identifier: application/vnd.app.geojson-feature+json; view=default
type GeoJSONFeature struct {
	Geometry   *GeoJSONGeometry       `form:"geometry" json:"geometry" yaml:"geometry" xml:"geometry"`
	Properties map[string]interface{} `form:"properties" json:"properties" yaml:"properties" xml:"properties"`
	Type       string                 `form:"type" json:"type" yaml:"type" xml:"type"`
}

// Validate validates the GeoJSONFeature media type instance.
func (mt *GeoJSONFeature) Validate() (err error) {
	if mt.Type == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "type"))
	}
	if mt.Geometry == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "geometry"))
	}
	if mt.Properties == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "properties"))
	}
	if mt.Geometry != nil {
		if err2 := mt.Geometry.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// DecodeGeoJSONFeature decodes the GeoJSONFeature instance encoded in resp body.
func (c *Client) DecodeGeoJSONFeature(resp *http.Response) (*GeoJSONFeature, error) {
	var decoded GeoJSONFeature
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// GeoJSONFeatureCollection is the media type for an array of GeoJSONFeature (default view)
//
// Identifier: application/vnd.app.geojson-feature+json; type=collection; view=default
type GeoJSONFeatureCollection []*GeoJSONFeature

// Validate validates the GeoJSONFeatureCollection media type instance.
func (mt GeoJSONFeatureCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeGeoJSONFeatureCollection decodes the GeoJSONFeatureCollection instance encoded in resp body.
func (c *Client) DecodeGeoJSONFeatureCollection(resp *http.Response) (GeoJSONFeatureCollection, error) {
	var decoded GeoJSONFeatureCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// GeoJSONGeometry media type (default view)
//
// Identifier: application/vnd.app.geojson-geometry+json; view=default
type GeoJSONGeometry struct {
	Coordinates []float64 `form:"coordinates" json:"coordinates" yaml:"coordinates" xml:"coordinates"`
	Type        string    `form:"type" json:"type" yaml:"type" xml:"type"`
}

// Validate validates the GeoJSONGeometry media type instance.
func (mt *GeoJSONGeometry) Validate() (err error) {
	if mt.Type == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "type"))
	}
	if mt.Coordinates == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "coordinates"))
	}
	return
}

// DecodeGeoJSONGeometry decodes the GeoJSONGeometry instance encoded in resp body.
func (c *Client) DecodeGeoJSONGeometry(resp *http.Response) (*GeoJSONGeometry, error) {
	var decoded GeoJSONGeometry
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// ClusterSummary media type (default view)
//
// Identifier: application/vnd.app.geometry_cluster_summary+json; view=default
type ClusterSummary struct {
	Centroid         []float64   `form:"centroid" json:"centroid" yaml:"centroid" xml:"centroid"`
	EndTime          time.Time   `form:"endTime" json:"endTime" yaml:"endTime" xml:"endTime"`
	Envelope         [][]float64 `form:"envelope,omitempty" json:"envelope,omitempty" yaml:"envelope,omitempty" xml:"envelope,omitempty"`
	ID               int         `form:"id" json:"id" yaml:"id" xml:"id"`
	NumberOfFeatures int         `form:"numberOfFeatures" json:"numberOfFeatures" yaml:"numberOfFeatures" xml:"numberOfFeatures"`
	Radius           float64     `form:"radius" json:"radius" yaml:"radius" xml:"radius"`
	SourceID         int         `form:"sourceId" json:"sourceId" yaml:"sourceId" xml:"sourceId"`
	StartTime        time.Time   `form:"startTime" json:"startTime" yaml:"startTime" xml:"startTime"`
}

// Validate validates the ClusterSummary media type instance.
func (mt *ClusterSummary) Validate() (err error) {

	if mt.Centroid == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "centroid"))
	}

	return
}

// DecodeClusterSummary decodes the ClusterSummary instance encoded in resp body.
func (c *Client) DecodeClusterSummary(resp *http.Response) (*ClusterSummary, error) {
	var decoded ClusterSummary
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// ClusterSummaryCollection is the media type for an array of ClusterSummary (default view)
//
// Identifier: application/vnd.app.geometry_cluster_summary+json; type=collection; view=default
type ClusterSummaryCollection []*ClusterSummary

// Validate validates the ClusterSummaryCollection media type instance.
func (mt ClusterSummaryCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeClusterSummaryCollection decodes the ClusterSummaryCollection instance encoded in resp body.
func (c *Client) DecodeClusterSummaryCollection(resp *http.Response) (ClusterSummaryCollection, error) {
	var decoded ClusterSummaryCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// FirmwareSummary media type (default view)
//
// Identifier: application/vnd.app.ifmrware+json; view=default
type FirmwareSummary struct {
	Etag    string    `form:"etag" json:"etag" yaml:"etag" xml:"etag"`
	ID      int       `form:"id" json:"id" yaml:"id" xml:"id"`
	Module  string    `form:"module" json:"module" yaml:"module" xml:"module"`
	Profile string    `form:"profile" json:"profile" yaml:"profile" xml:"profile"`
	Time    time.Time `form:"time" json:"time" yaml:"time" xml:"time"`
	URL     string    `form:"url" json:"url" yaml:"url" xml:"url"`
}

// Validate validates the FirmwareSummary media type instance.
func (mt *FirmwareSummary) Validate() (err error) {

	if mt.Etag == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "etag"))
	}
	if mt.Module == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "module"))
	}
	if mt.Profile == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "profile"))
	}
	if mt.URL == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "url"))
	}
	return
}

// DecodeFirmwareSummary decodes the FirmwareSummary instance encoded in resp body.
func (c *Client) DecodeFirmwareSummary(resp *http.Response) (*FirmwareSummary, error) {
	var decoded FirmwareSummary
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// FirmwareSummaryCollection is the media type for an array of FirmwareSummary (default view)
//
// Identifier: application/vnd.app.ifmrware+json; type=collection; view=default
type FirmwareSummaryCollection []*FirmwareSummary

// Validate validates the FirmwareSummaryCollection media type instance.
func (mt FirmwareSummaryCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeFirmwareSummaryCollection decodes the FirmwareSummaryCollection instance encoded in resp body.
func (c *Client) DecodeFirmwareSummaryCollection(resp *http.Response) (FirmwareSummaryCollection, error) {
	var decoded FirmwareSummaryCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// Location media type (default view)
//
// Identifier: application/vnd.app.location+json; view=default
type Location struct {
	Location string `form:"location" json:"location" yaml:"location" xml:"location"`
}

// Validate validates the Location media type instance.
func (mt *Location) Validate() (err error) {
	if mt.Location == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "location"))
	}
	if err2 := goa.ValidateFormat(goa.FormatURI, mt.Location); err2 != nil {
		err = goa.MergeErrors(err, goa.InvalidFormatError(`response.location`, mt.Location, goa.FormatURI, err2))
	}
	return
}

// DecodeLocation decodes the Location instance encoded in resp body.
func (c *Client) DecodeLocation(resp *http.Response) (*Location, error) {
	var decoded Location
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// MapFeatures media type (default view)
//
// Identifier: application/vnd.app.map_features+json; view=default
type MapFeatures struct {
	GeoJSON    *PagedGeoJSON                    `form:"geoJSON" json:"geoJSON" yaml:"geoJSON" xml:"geoJSON"`
	Geometries ClusterGeometrySummaryCollection `form:"geometries" json:"geometries" yaml:"geometries" xml:"geometries"`
	Spatial    ClusterSummaryCollection         `form:"spatial" json:"spatial" yaml:"spatial" xml:"spatial"`
	Temporal   ClusterSummaryCollection         `form:"temporal" json:"temporal" yaml:"temporal" xml:"temporal"`
}

// Validate validates the MapFeatures media type instance.
func (mt *MapFeatures) Validate() (err error) {
	if mt.GeoJSON == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "geoJSON"))
	}
	if mt.Temporal == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "temporal"))
	}
	if mt.Spatial == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "spatial"))
	}
	if mt.Geometries == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "geometries"))
	}
	if mt.GeoJSON != nil {
		if err2 := mt.GeoJSON.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if err2 := mt.Geometries.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	if err2 := mt.Spatial.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	if err2 := mt.Temporal.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeMapFeatures decodes the MapFeatures instance encoded in resp body.
func (c *Client) DecodeMapFeatures(resp *http.Response) (*MapFeatures, error) {
	var decoded MapFeatures
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// TeamMember media type (default view)
//
// Identifier: application/vnd.app.member+json; view=default
type TeamMember struct {
	Role   string `form:"role" json:"role" yaml:"role" xml:"role"`
	TeamID int    `form:"teamId" json:"teamId" yaml:"teamId" xml:"teamId"`
	UserID int    `form:"userId" json:"userId" yaml:"userId" xml:"userId"`
}

// Validate validates the TeamMember media type instance.
func (mt *TeamMember) Validate() (err error) {

	if mt.Role == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "role"))
	}
	return
}

// DecodeTeamMember decodes the TeamMember instance encoded in resp body.
func (c *Client) DecodeTeamMember(resp *http.Response) (*TeamMember, error) {
	var decoded TeamMember
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// TeamMemberCollection is the media type for an array of TeamMember (default view)
//
// Identifier: application/vnd.app.member+json; type=collection; view=default
type TeamMemberCollection []*TeamMember

// Validate validates the TeamMemberCollection media type instance.
func (mt TeamMemberCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeTeamMemberCollection decodes the TeamMemberCollection instance encoded in resp body.
func (c *Client) DecodeTeamMemberCollection(resp *http.Response) (TeamMemberCollection, error) {
	var decoded TeamMemberCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// TeamMembers media type (default view)
//
// Identifier: application/vnd.app.members+json; view=default
type TeamMembers struct {
	Members TeamMemberCollection `form:"members" json:"members" yaml:"members" xml:"members"`
}

// Validate validates the TeamMembers media type instance.
func (mt *TeamMembers) Validate() (err error) {
	if mt.Members == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "members"))
	}
	if err2 := mt.Members.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeTeamMembers decodes the TeamMembers instance encoded in resp body.
func (c *Client) DecodeTeamMembers(resp *http.Response) (*TeamMembers, error) {
	var decoded TeamMembers
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// PagedGeoJSON media type (default view)
//
// Identifier: application/vnd.app.paged_geojson+json; view=default
type PagedGeoJSON struct {
	Geo         *GeoJSON `form:"geo" json:"geo" yaml:"geo" xml:"geo"`
	HasMore     bool     `form:"hasMore" json:"hasMore" yaml:"hasMore" xml:"hasMore"`
	NextURL     string   `form:"nextUrl" json:"nextUrl" yaml:"nextUrl" xml:"nextUrl"`
	PreviousURL *string  `form:"previousUrl,omitempty" json:"previousUrl,omitempty" yaml:"previousUrl,omitempty" xml:"previousUrl,omitempty"`
}

// Validate validates the PagedGeoJSON media type instance.
func (mt *PagedGeoJSON) Validate() (err error) {
	if mt.NextURL == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "nextUrl"))
	}
	if mt.Geo == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "geo"))
	}

	if mt.Geo != nil {
		if err2 := mt.Geo.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// DecodePagedGeoJSON decodes the PagedGeoJSON instance encoded in resp body.
func (c *Client) DecodePagedGeoJSON(resp *http.Response) (*PagedGeoJSON, error) {
	var decoded PagedGeoJSON
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// Project media type (default view)
//
// Identifier: application/vnd.app.project+json; view=default
type Project struct {
	Description string `form:"description" json:"description" yaml:"description" xml:"description"`
	ID          int    `form:"id" json:"id" yaml:"id" xml:"id"`
	Name        string `form:"name" json:"name" yaml:"name" xml:"name"`
	Slug        string `form:"slug" json:"slug" yaml:"slug" xml:"slug"`
}

// Validate validates the Project media type instance.
func (mt *Project) Validate() (err error) {

	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	if mt.Slug == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "slug"))
	}
	if mt.Description == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "description"))
	}
	if ok := goa.ValidatePattern(`^[[:alnum:]]+(-[[:alnum:]]+)*$`, mt.Slug); !ok {
		err = goa.MergeErrors(err, goa.InvalidPatternError(`response.slug`, mt.Slug, `^[[:alnum:]]+(-[[:alnum:]]+)*$`))
	}
	if utf8.RuneCountInString(mt.Slug) > 40 {
		err = goa.MergeErrors(err, goa.InvalidLengthError(`response.slug`, mt.Slug, utf8.RuneCountInString(mt.Slug), 40, false))
	}
	return
}

// DecodeProject decodes the Project instance encoded in resp body.
func (c *Client) DecodeProject(resp *http.Response) (*Project, error) {
	var decoded Project
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// ProjectCollection is the media type for an array of Project (default view)
//
// Identifier: application/vnd.app.project+json; type=collection; view=default
type ProjectCollection []*Project

// Validate validates the ProjectCollection media type instance.
func (mt ProjectCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeProjectCollection decodes the ProjectCollection instance encoded in resp body.
func (c *Client) DecodeProjectCollection(resp *http.Response) (ProjectCollection, error) {
	var decoded ProjectCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// Projects media type (default view)
//
// Identifier: application/vnd.app.projects+json; view=default
type Projects struct {
	Projects ProjectCollection `form:"projects" json:"projects" yaml:"projects" xml:"projects"`
}

// Validate validates the Projects media type instance.
func (mt *Projects) Validate() (err error) {
	if mt.Projects == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "projects"))
	}
	if err2 := mt.Projects.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeProjects decodes the Projects instance encoded in resp body.
func (c *Client) DecodeProjects(resp *http.Response) (*Projects, error) {
	var decoded Projects
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// QueryData media type (default view)
//
// Identifier: application/vnd.app.queried+json; view=default
type QueryData struct {
	Series SeriesDataCollection `form:"series" json:"series" yaml:"series" xml:"series"`
}

// Validate validates the QueryData media type instance.
func (mt *QueryData) Validate() (err error) {
	if mt.Series == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "series"))
	}
	if err2 := mt.Series.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeQueryData decodes the QueryData instance encoded in resp body.
func (c *Client) DecodeQueryData(resp *http.Response) (*QueryData, error) {
	var decoded QueryData
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// ReadingSummary media type (default view)
//
// Identifier: application/vnd.app.reading_summary+json; view=default
type ReadingSummary struct {
	Name string `form:"name" json:"name" yaml:"name" xml:"name"`
}

// Validate validates the ReadingSummary media type instance.
func (mt *ReadingSummary) Validate() (err error) {
	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	return
}

// DecodeReadingSummary decodes the ReadingSummary instance encoded in resp body.
func (c *Client) DecodeReadingSummary(resp *http.Response) (*ReadingSummary, error) {
	var decoded ReadingSummary
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// ReadingSummaryCollection is the media type for an array of ReadingSummary (default view)
//
// Identifier: application/vnd.app.reading_summary+json; type=collection; view=default
type ReadingSummaryCollection []*ReadingSummary

// Validate validates the ReadingSummaryCollection media type instance.
func (mt ReadingSummaryCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeReadingSummaryCollection decodes the ReadingSummaryCollection instance encoded in resp body.
func (c *Client) DecodeReadingSummaryCollection(resp *http.Response) (ReadingSummaryCollection, error) {
	var decoded ReadingSummaryCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// SeriesData media type (default view)
//
// Identifier: application/vnd.app.series+json; view=default
type SeriesData struct {
	Name string        `form:"name" json:"name" yaml:"name" xml:"name"`
	Rows []interface{} `form:"rows" json:"rows" yaml:"rows" xml:"rows"`
}

// Validate validates the SeriesData media type instance.
func (mt *SeriesData) Validate() (err error) {
	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	if mt.Rows == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "rows"))
	}
	return
}

// DecodeSeriesData decodes the SeriesData instance encoded in resp body.
func (c *Client) DecodeSeriesData(resp *http.Response) (*SeriesData, error) {
	var decoded SeriesData
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// SeriesDataCollection is the media type for an array of SeriesData (default view)
//
// Identifier: application/vnd.app.series+json; type=collection; view=default
type SeriesDataCollection []*SeriesData

// Validate validates the SeriesDataCollection media type instance.
func (mt SeriesDataCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeSeriesDataCollection decodes the SeriesDataCollection instance encoded in resp body.
func (c *Client) DecodeSeriesDataCollection(resp *http.Response) (SeriesDataCollection, error) {
	var decoded SeriesDataCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// Source media type (default view)
//
// Identifier: application/vnd.app.source+json; view=default
type Source struct {
	Active       *bool  `form:"active,omitempty" json:"active,omitempty" yaml:"active,omitempty" xml:"active,omitempty"`
	ExpeditionID int    `form:"expeditionId" json:"expeditionId" yaml:"expeditionId" xml:"expeditionId"`
	ID           int    `form:"id" json:"id" yaml:"id" xml:"id"`
	Name         string `form:"name" json:"name" yaml:"name" xml:"name"`
	TeamID       *int   `form:"teamId,omitempty" json:"teamId,omitempty" yaml:"teamId,omitempty" xml:"teamId,omitempty"`
	UserID       *int   `form:"userId,omitempty" json:"userId,omitempty" yaml:"userId,omitempty" xml:"userId,omitempty"`
}

// Validate validates the Source media type instance.
func (mt *Source) Validate() (err error) {

	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	return
}

// DecodeSource decodes the Source instance encoded in resp body.
func (c *Client) DecodeSource(resp *http.Response) (*Source, error) {
	var decoded Source
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// SourceSummary media type (default view)
//
// Identifier: application/vnd.app.source_summary+json; view=default
type SourceSummary struct {
	ID       int                      `form:"id" json:"id" yaml:"id" xml:"id"`
	Name     string                   `form:"name" json:"name" yaml:"name" xml:"name"`
	Readings ReadingSummaryCollection `form:"readings,omitempty" json:"readings,omitempty" yaml:"readings,omitempty" xml:"readings,omitempty"`
	Spatial  ClusterSummaryCollection `form:"spatial" json:"spatial" yaml:"spatial" xml:"spatial"`
	Temporal ClusterSummaryCollection `form:"temporal" json:"temporal" yaml:"temporal" xml:"temporal"`
}

// Validate validates the SourceSummary media type instance.
func (mt *SourceSummary) Validate() (err error) {

	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	if mt.Temporal == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "temporal"))
	}
	if mt.Spatial == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "spatial"))
	}
	if err2 := mt.Readings.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	if err2 := mt.Spatial.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	if err2 := mt.Temporal.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeSourceSummary decodes the SourceSummary instance encoded in resp body.
func (c *Client) DecodeSourceSummary(resp *http.Response) (*SourceSummary, error) {
	var decoded SourceSummary
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// SourceToken media type (default view)
//
// Identifier: application/vnd.app.source_token+json; view=default
type SourceToken struct {
	ExpeditionID int    `form:"expeditionId" json:"expeditionId" yaml:"expeditionId" xml:"expeditionId"`
	ID           int    `form:"id" json:"id" yaml:"id" xml:"id"`
	Token        string `form:"token" json:"token" yaml:"token" xml:"token"`
}

// Validate validates the SourceToken media type instance.
func (mt *SourceToken) Validate() (err error) {

	if mt.Token == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "token"))
	}

	return
}

// DecodeSourceToken decodes the SourceToken instance encoded in resp body.
func (c *Client) DecodeSourceToken(resp *http.Response) (*SourceToken, error) {
	var decoded SourceToken
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// SourceTokenCollection is the media type for an array of SourceToken (default view)
//
// Identifier: application/vnd.app.source_token+json; type=collection; view=default
type SourceTokenCollection []*SourceToken

// Validate validates the SourceTokenCollection media type instance.
func (mt SourceTokenCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeSourceTokenCollection decodes the SourceTokenCollection instance encoded in resp body.
func (c *Client) DecodeSourceTokenCollection(resp *http.Response) (SourceTokenCollection, error) {
	var decoded SourceTokenCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// SourceTokens media type (default view)
//
// Identifier: application/vnd.app.source_tokens+json; view=default
type SourceTokens struct {
	SourceTokens SourceTokenCollection `form:"sourceTokens" json:"sourceTokens" yaml:"sourceTokens" xml:"sourceTokens"`
}

// Validate validates the SourceTokens media type instance.
func (mt *SourceTokens) Validate() (err error) {
	if mt.SourceTokens == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "sourceTokens"))
	}
	if err2 := mt.SourceTokens.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeSourceTokens decodes the SourceTokens instance encoded in resp body.
func (c *Client) DecodeSourceTokens(resp *http.Response) (*SourceTokens, error) {
	var decoded SourceTokens
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// Sources media type (default view)
//
// Identifier: application/vnd.app.sources+json; view=default
type Sources struct {
	DeviceSources         DeviceSourceCollection         `form:"deviceSources,omitempty" json:"deviceSources,omitempty" yaml:"deviceSources,omitempty" xml:"deviceSources,omitempty"`
	TwitterAccountSources TwitterAccountSourceCollection `form:"twitterAccountSources,omitempty" json:"twitterAccountSources,omitempty" yaml:"twitterAccountSources,omitempty" xml:"twitterAccountSources,omitempty"`
}

// Validate validates the Sources media type instance.
func (mt *Sources) Validate() (err error) {
	if err2 := mt.DeviceSources.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	if err2 := mt.TwitterAccountSources.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeSources decodes the Sources instance encoded in resp body.
func (c *Client) DecodeSources(resp *http.Response) (*Sources, error) {
	var decoded Sources
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// Team media type (default view)
//
// Identifier: application/vnd.app.team+json; view=default
type Team struct {
	Description string `form:"description" json:"description" yaml:"description" xml:"description"`
	ID          int    `form:"id" json:"id" yaml:"id" xml:"id"`
	Name        string `form:"name" json:"name" yaml:"name" xml:"name"`
	Slug        string `form:"slug" json:"slug" yaml:"slug" xml:"slug"`
}

// Validate validates the Team media type instance.
func (mt *Team) Validate() (err error) {

	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	if mt.Slug == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "slug"))
	}
	if mt.Description == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "description"))
	}
	if ok := goa.ValidatePattern(`\S`, mt.Name); !ok {
		err = goa.MergeErrors(err, goa.InvalidPatternError(`response.name`, mt.Name, `\S`))
	}
	if utf8.RuneCountInString(mt.Name) > 256 {
		err = goa.MergeErrors(err, goa.InvalidLengthError(`response.name`, mt.Name, utf8.RuneCountInString(mt.Name), 256, false))
	}
	if ok := goa.ValidatePattern(`^[[:alnum:]]+(-[[:alnum:]]+)*$`, mt.Slug); !ok {
		err = goa.MergeErrors(err, goa.InvalidPatternError(`response.slug`, mt.Slug, `^[[:alnum:]]+(-[[:alnum:]]+)*$`))
	}
	if utf8.RuneCountInString(mt.Slug) > 40 {
		err = goa.MergeErrors(err, goa.InvalidLengthError(`response.slug`, mt.Slug, utf8.RuneCountInString(mt.Slug), 40, false))
	}
	return
}

// DecodeTeam decodes the Team instance encoded in resp body.
func (c *Client) DecodeTeam(resp *http.Response) (*Team, error) {
	var decoded Team
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// TeamCollection is the media type for an array of Team (default view)
//
// Identifier: application/vnd.app.team+json; type=collection; view=default
type TeamCollection []*Team

// Validate validates the TeamCollection media type instance.
func (mt TeamCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeTeamCollection decodes the TeamCollection instance encoded in resp body.
func (c *Client) DecodeTeamCollection(resp *http.Response) (TeamCollection, error) {
	var decoded TeamCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// Teams media type (default view)
//
// Identifier: application/vnd.app.teams+json; view=default
type Teams struct {
	Teams TeamCollection `form:"teams" json:"teams" yaml:"teams" xml:"teams"`
}

// Validate validates the Teams media type instance.
func (mt *Teams) Validate() (err error) {
	if mt.Teams == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "teams"))
	}
	if err2 := mt.Teams.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeTeams decodes the Teams instance encoded in resp body.
func (c *Client) DecodeTeams(resp *http.Response) (*Teams, error) {
	var decoded Teams
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// TwitterAccountSources media type (default view)
//
// Identifier: application/vnd.app.twitter_account_intputs+json; view=default
type TwitterAccountSources struct {
	TwitterAccountSources TwitterAccountSourceCollection `form:"twitterAccountSources" json:"twitterAccountSources" yaml:"twitterAccountSources" xml:"twitterAccountSources"`
}

// Validate validates the TwitterAccountSources media type instance.
func (mt *TwitterAccountSources) Validate() (err error) {
	if mt.TwitterAccountSources == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "twitterAccountSources"))
	}
	if err2 := mt.TwitterAccountSources.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeTwitterAccountSources decodes the TwitterAccountSources instance encoded in resp body.
func (c *Client) DecodeTwitterAccountSources(resp *http.Response) (*TwitterAccountSources, error) {
	var decoded TwitterAccountSources
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// TwitterAccountSource media type (default view)
//
// Identifier: application/vnd.app.twitter_account_source+json; view=default
type TwitterAccountSource struct {
	ExpeditionID     int    `form:"expeditionId" json:"expeditionId" yaml:"expeditionId" xml:"expeditionId"`
	ID               int    `form:"id" json:"id" yaml:"id" xml:"id"`
	Name             string `form:"name" json:"name" yaml:"name" xml:"name"`
	ScreenName       string `form:"screenName" json:"screenName" yaml:"screenName" xml:"screenName"`
	TeamID           *int   `form:"teamId,omitempty" json:"teamId,omitempty" yaml:"teamId,omitempty" xml:"teamId,omitempty"`
	TwitterAccountID int    `form:"twitterAccountId" json:"twitterAccountId" yaml:"twitterAccountId" xml:"twitterAccountId"`
	UserID           *int   `form:"userId,omitempty" json:"userId,omitempty" yaml:"userId,omitempty" xml:"userId,omitempty"`
}

// Validate validates the TwitterAccountSource media type instance.
func (mt *TwitterAccountSource) Validate() (err error) {

	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}

	if mt.ScreenName == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "screenName"))
	}
	return
}

// DecodeTwitterAccountSource decodes the TwitterAccountSource instance encoded in resp body.
func (c *Client) DecodeTwitterAccountSource(resp *http.Response) (*TwitterAccountSource, error) {
	var decoded TwitterAccountSource
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// TwitterAccountSourceCollection is the media type for an array of TwitterAccountSource (default view)
//
// Identifier: application/vnd.app.twitter_account_source+json; type=collection; view=default
type TwitterAccountSourceCollection []*TwitterAccountSource

// Validate validates the TwitterAccountSourceCollection media type instance.
func (mt TwitterAccountSourceCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeTwitterAccountSourceCollection decodes the TwitterAccountSourceCollection instance encoded in resp body.
func (c *Client) DecodeTwitterAccountSourceCollection(resp *http.Response) (TwitterAccountSourceCollection, error) {
	var decoded TwitterAccountSourceCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// User media type (default view)
//
// Identifier: application/vnd.app.user+json; view=default
type User struct {
	Bio   string `form:"bio" json:"bio" yaml:"bio" xml:"bio"`
	Email string `form:"email" json:"email" yaml:"email" xml:"email"`
	ID    int    `form:"id" json:"id" yaml:"id" xml:"id"`
	Name  string `form:"name" json:"name" yaml:"name" xml:"name"`
	// Username
	Username string `form:"username" json:"username" yaml:"username" xml:"username"`
}

// Validate validates the User media type instance.
func (mt *User) Validate() (err error) {

	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	if mt.Username == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "username"))
	}
	if mt.Email == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "email"))
	}
	if mt.Bio == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "bio"))
	}
	if err2 := goa.ValidateFormat(goa.FormatEmail, mt.Email); err2 != nil {
		err = goa.MergeErrors(err, goa.InvalidFormatError(`response.email`, mt.Email, goa.FormatEmail, err2))
	}
	if ok := goa.ValidatePattern(`\S`, mt.Name); !ok {
		err = goa.MergeErrors(err, goa.InvalidPatternError(`response.name`, mt.Name, `\S`))
	}
	if utf8.RuneCountInString(mt.Name) > 256 {
		err = goa.MergeErrors(err, goa.InvalidLengthError(`response.name`, mt.Name, utf8.RuneCountInString(mt.Name), 256, false))
	}
	if ok := goa.ValidatePattern(`^[\dA-Za-z]+(?:-[\dA-Za-z]+)*$`, mt.Username); !ok {
		err = goa.MergeErrors(err, goa.InvalidPatternError(`response.username`, mt.Username, `^[\dA-Za-z]+(?:-[\dA-Za-z]+)*$`))
	}
	if utf8.RuneCountInString(mt.Username) > 40 {
		err = goa.MergeErrors(err, goa.InvalidLengthError(`response.username`, mt.Username, utf8.RuneCountInString(mt.Username), 40, false))
	}
	return
}

// DecodeUser decodes the User instance encoded in resp body.
func (c *Client) DecodeUser(resp *http.Response) (*User, error) {
	var decoded User
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// UserCollection is the media type for an array of User (default view)
//
// Identifier: application/vnd.app.user+json; type=collection; view=default
type UserCollection []*User

// Validate validates the UserCollection media type instance.
func (mt UserCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// DecodeUserCollection decodes the UserCollection instance encoded in resp body.
func (c *Client) DecodeUserCollection(resp *http.Response) (UserCollection, error) {
	var decoded UserCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// Users media type (default view)
//
// Identifier: application/vnd.app.users+json; view=default
type Users struct {
	Users UserCollection `form:"users" json:"users" yaml:"users" xml:"users"`
}

// Validate validates the Users media type instance.
func (mt *Users) Validate() (err error) {
	if mt.Users == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "users"))
	}
	if err2 := mt.Users.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// DecodeUsers decodes the Users instance encoded in resp body.
func (c *Client) DecodeUsers(resp *http.Response) (*Users, error) {
	var decoded Users
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// DecodeErrorResponse decodes the ErrorResponse instance encoded in resp body.
func (c *Client) DecodeErrorResponse(resp *http.Response) (*goa.ErrorResponse, error) {
	var decoded goa.ErrorResponse
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}
