// Code generated by goagen v1.1.0, command line:
// $ main
//
// API "fieldkit": picture Resource Client
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"fmt"
	"golang.org/x/net/context"
	"net/http"
	"net/url"
	"strconv"
)

// GetIDPicturePath computes a request path to the get id action of picture.
func GetIDPicturePath(userID int) string {
	param0 := strconv.Itoa(userID)

	return fmt.Sprintf("/users/%s/picture", param0)
}

// List a project's inputs
func (c *Client) GetIDPicture(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGetIDPictureRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetIDPictureRequest create the request corresponding to the get id action endpoint of the picture resource.
func (c *Client) NewGetIDPictureRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
