export const INITIALIZE = "INITIALIZE";
export const LOGIN = "LOGIN";
export const AUTHENTICATED = "AUTHENTICATED";
export const LOGOUT = "LOGOUT";

export const NEED_COMMON = "NEED_COMMON";
export const NEED_PROJECTS = "NEED_PROJECTS";
export const NEED_STATIONS = "NEED_STATIONS";
export const NEED_PROJECT = "NEED_PROJECT";
export const NEED_STATION = "NEED_STATION";

export const STATION_PROJECT_ADD = "STATION_PROJECT_ADD";
export const STATION_PROJECT_REMOVE = "STATION_PROJECT_REMOVE";

// User

export const REFRESH_CURRENT_USER = "REFRESH_CURRENT_USER";
export const UPLOAD_USER_PHOTO = "UPLOAD_USER_PHOTO";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

// Projects

export const PROJECT_FOLLOW = "PROJECT_FOLLOW";
export const PROJECT_UNFOLLOW = "PROJECT_UNFOLLOW";
export const PROJECT_INVITE = "PROJECT_INVITE";
export const PROJECT_REMOVE = "PROJECT_REMOVE";
export const ACCEPT_PROJECT_INVITE = "ACCEPT_PROJECT_INVITE";
export const DECLINE_PROJECT_INVITE = "DECLINE_PROJECT_INVITE";
export const SAVE_PROJECT = "SAVE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
